kind: PersistentVolume
apiVersion: v1
metadata:
  name: test
  labels:
    type: quobyte
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "base"
  quobyte:
    # the registry parameter was an required parameter, but is not used anymore.
    # It's here for API compatibility.
    registry: ignored:7861
    volume: test
    readOnly: false
    user: root
    group: root
