apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: base
provisioner: kubernetes.io/quobyte
parameters:
    quobyteAPIServer: "http://api.quobyte:7860"
    registry: "registry.quobyte:7861"
    adminSecretName: "quobyte-admin-secret"
    adminSecretNamespace: "kube-system"
    user: "root"
    group: "root"
    quobyteConfig: "BASE"
# For kubernetes < 1.10.2, quobyteTenant needs point to the tenant's uuid.
# Later versions are able to resolve the tenant's name.
    quobyteTenant: "<uuid of tenant>"
    createQuota: "False"
reclaimPolicy: Retain
